language: objective-c
script:
 - xcodebuild -project Calculator.xcodeproj -scheme Calculator -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=10.3.1, name=iPhone 5' build test | xcpretty -c --test --color
