language: objective-c
osx_image: xcode8.1
before_install:
 - brew update
script:
 - xcodebuild -project Calculator.xcodeproj -scheme Calculator -sdk iphonesimulator -destination 'platform=iOS Simulator' clean test | xcpretty -c --test --color
