language: objective-c
osx_image: xcode8.1
before_install:
 - brew update
script:
 - xcodebuild -project Calculator.xcodeproj -scheme Calculator -sdk iphonesimulator -destination 'id=0EB7E0E4-915F-497E-9D1C-934A10FA82E3' clean build test | xcpretty -c --test --color
