language: objective-c
script:
 - xcodebuild -project Calculator.xcodeproj -scheme Calculator -sdk iphonesimulator -destination 'platform=iOS Simulator, id=2523EF7F-852D-4268-A9A3-C55A4428EAE0, OS=10.3.1, name=iPhone 5' build test | xcpretty -c --test --color
