language: objective-c
before_install:
 - brew update
script:
 - xcodebuild -project Calculator.xcodeproj -scheme CalculatorTests -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=10.3.1, name=iPhone 5' build test | xcpretty -c --test --color
