language: objective-c
osx_image: xcode8.3
before_install:
 - brew update
script:
 - xcodebuild -project Calculator.xcodeproj -scheme Calculator -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=11.0,name=iPhone 5s' clean build test | xcpretty -c --test --color
